---
abstract: 'Plural inflection for ENG.'
author:
  - 'Damian Conway <damian@conway.org>'
build_requires:
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-ENG-Inflect
requires:
  Env: 0
  Exporter: 0
  strict: 0
  vars: 0
version: 0.0577
